version: '3'

services:
  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always 
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web 

volumes:
  web-django:
  web-static: