# Generated by Django 3.1.7 on 2021-03-10 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('technology', models.CharField(max_length=200)),
                ('long_description', models.TextField()),
                ('what_i_learned', models.TextField()),
                ('wish_i_knew_before', models.TextField()),
                ('how_i_would_improve_it', models.TextField()),
                ('demo_url', models.URLField()),
                ('github_url', models.URLField()),
                ('thumbnail_image_url', models.URLField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
