# Generated by Django 3.1.7 on 2021-03-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='how_i_would_improve_it',
            new_name='additional_notes',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='what_i_learned',
            new_name='stack',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='wish_i_knew_before',
            new_name='wish_list',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
    ]
