# Generated by Django 3.1.7 on 2021-03-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagline',
        ),
    ]
