# Generated by Django 3.1.7 on 2021-03-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagline',
            field=models.CharField(default='Example tagline. Need to update.', max_length=200),
            preserve_default=False,
        ),
    ]
