# Generated by Django 3.1.7 on 2021-03-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='image_url', upload_to=''),
            preserve_default=False,
        ),
    ]
